### ISSUE TITLE
Create trait for attach files for model

### ISSUE THREAD

**Issue by ponich** [Ponich/eloquent-traits#2]
**todo:** 

- [x] use storage disks

- [x] attach method can take `Illuminate\Http\UploadedFile` | `Illuminate\Support\Facades\File` | absolute path 

- [ ] if type of file is image, create -  thumbnail
 > Is it necessary?
 
- [ ] generate attribute for get url

[Branch for this trait](https://github.com/ponich/eloquent-traits/tree/attach01)
